### ISSUE TITLE
The Logo and QR code is broken

### ISSUE THREAD

**Issue by chankruze** [geekofia/blog#12]
URL: https://blog.geekofia.tk/

![image](https://user-images.githubusercontent.com/29806845/147928298-142221a5-4607-475d-978a-edc20cec7f2d.png)

**Comment by ishaanbedi** [comment]
Hey! Can you assign this issue to me?

**Comment by chankruze** [comment]
> Hey! Can you assign this issue to me?

Yes, sure!

**Comment by ishaanbedi** [comment]
Alright! Working on it!
